name: Build

on:
  push:
  pull_request:

jobs:
  flutter:
    runs-on: ubuntu-latest
    container: cirrusci/flutter:latest
    steps:
      - uses: actions/checkout@v2

      - name: Execute test script
        run: flutter test